name: CI devops 2023

on:
  #to begin you want to launch this job in main and develop
  push:
    branches: master
  pull_request:

defaults:
  run:
    working-directory: ./TP01/backend/simple-api-student

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn -B clean verify --file pom.xml
        
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops/simple-api

      - name: Build image and push database
        working-directory: ..
        run: ls .


      - name: Build image and push httpd
        run: ls .
